name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        uses: espadrine/huggingface-spaces-sync-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          huggingface_token: ${{ secrets.HF_TOKEN }}
          huggingface_repo: asermnasr/figranium-testing
          huggingface_branch: main
