name: Sync to Hugging Face Hub

on:
  push:
    branches: [main, dev]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync to Hugging Face
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: asermnasr/figranium-testing
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: docker
